### ISSUE TITLE
[Bug]A new update is sending me into safe mode

### ISSUE THREAD

**Issue by House-Coulybaly** [Janisbtw/Glance#10]
When I update the tweak it sends me directly in to safe mode, on iPhone 8 Panera1n rootless jailbreak iOS 16.7.4

**Comment by tonynene** [comment]
the new update is sending me to safe mode on iPhone 13 pro max, dopamine 2, ios 15.3.1

**Comment by ibrahimqatar** [comment]
Having the same problem and provided the crashlog in my other post. 1.1.1 is released but I think there is no rootless version?

**Comment by Janisbtw** [comment]
Hey, I've released an update to address these issues. Thanks for your report!
