### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by pkgFiles** [Janisbtw/Glance#14]
Preference bundles are gray. No options visible. (Comet installed, iOS 15.1, Xina 1.1.7.2)![image](https://github.com/Janisbtw/Glance/assets/100750060/a4bc3728-26d0-4b3f-a5c7-01f33708c022)

**Comment by pkgFiles** [comment]
Did some research. Preferences does work on 1.0 but not > 1.0

**Comment by RUGMJ** [comment]
did you purchase the tweak legitimately?

**Comment by pkgFiles** [comment]
Sure, today. ![image](https://github.com/Janisbtw/Glance/assets/100750060/1c9765e3-520c-459f-98ec-e2e4c0c17628)

**Comment by RUGMJ** [comment]
only because it looked like a drm issue, do you by chance have pinnacle? that uses the same preference framework (Comet). If you don't pinnacle is OS (see my gh)

**Comment by pkgFiles** [comment]
Pinnacle preferences works fine. ![image](https://github.com/Janisbtw/Glance/assets/100750060/df35b203-a481-4058-b2c4-c18075625c25)

**Comment by Janisbtw** [comment]
Hey, thanks for the report. I suspect it's something related to Xina. Just to make sure, you didn't manually change something about the file structure (e.g. unlinking /var/LIY/)?

**Comment by Janisbtw** [comment]
Actually, can you try either using Dopamine or upgrading to Xina v2?

**Comment by pkgFiles** [comment]
No this is not an option, tweaks (especially DRM's) should handle this.

**Comment by RUGMJ** [comment]
@Janisbtw this shouldnt be an issue with xina since it works fine with pinnacle too. But xina is kinda dead
