### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Bmxvu** [Janisbtw/Glance#15]
Hey my phone keeps going straight into safemode and crashing after I install the tweak I’m on iOS 16.5 iPhone 12 dopamine jailbreak I have the crash log but can’t paste it here because it is too long if u add my discord Bmxu_  i can send the crash log please help me i really don’t want a refund I just want to be able to use the tweak but I will attach a file for the crash log 
[text.txt](https://github.com/user-attachments/files/15945659/text.txt)

**Comment by Janisbtw** [comment]
Hey, thanks for the report. That crash seems to be caused by Flora, not Glance

**Comment by Bmxvu** [comment]
That fixed it I’m going to send the crash log to the tweak developer of Flora
