### ISSUE TITLE
Enable button is greyed out with an error (16.0.3, Dopamine 2)

### ISSUE THREAD

**Issue by ibrahimqatar** [Janisbtw/Glance#16]
![image](https://github.com/user-attachments/assets/bc39bd00-d08a-4b20-bd62-9e00831052f6)

![image](https://github.com/user-attachments/assets/9eb3f8bf-e6b9-4367-b757-a3746bf564d8)

**Comment by Janisbtw** [comment]
Try logging out of Chariz in Sileo and logging in again

**Comment by ibrahimqatar** [comment]
Thanks that worked!
