### ISSUE TITLE
Tweak “enable” button greyed out and error message pops up

### ISSUE THREAD

**Issue by EyalRotem** [Janisbtw/Glance#20]
Hi,
Using iPhone 14 pro, iOS 16.3.1, dopamine.
After installing the tweak it appeared in the settings- but wasn’t enabled - and the option was greyed out -
![6E3C4C16-6608-49C2-8D7D-4F22FCDE7C59](https://github.com/user-attachments/assets/71a500a8-fb9c-4935-baf9-776c782637b3)

after a second or so a popup appears-
![A429F700-33C5-48C2-90DA-AFA552722E59](https://github.com/user-attachments/assets/2e03fed5-913c-41f5-9790-a5d39b7d28ac)

 No idea what causes this, any tweak incompatibility?

**Comment by Janisbtw** [comment]
Hey, thanks for buying the tweak. Try logging out of Chariz in Sileo and then log back in. Let me know if that fixes it

**Comment by EyalRotem** [comment]
That actually worked!

maybe try better error handling with more informative info - might reduce overhead for you on the long run😅

thanks!
