### ISSUE TITLE
[bug] FaceID lock icon shows and status bar flashes when the icon fades

### ISSUE THREAD

**Issue by ibrahimqatar** [Janisbtw/Glance#5]
FaceID shows on my iPhone 14 Pro Max which I think should be hidden.

Also,when status bar is hidden, it shows for a less that a second when the icon fades away (the lockscreen itself shows briefly as well)

**Comment by Janisbtw** [comment]
Hi, can you send a screenshot of the faceid stuff you mean? The other thing should be a simple fix
